develop_manager:
  home:
    index: '主页-我的文件'
    cytoscape: '文件关系图'
    files_search: '全局检索'
  products:
    index: '产品-列表'
    show: '产品-详情'
    new: '产品-添加界面'
    create: '产品-添加'
    edit: '产品-编辑界面'
    update: '产品-编辑'
    destroy: '产品-删除'
    show_version: '产品-历史版本'
    upload_file: '产品-上传图纸界面'
    do_upload_file: '产品-上传图纸'
    edit_file: '产品-编辑图纸界面'
    update_file: '产品-编辑图纸'
    apply: '产品-申请审批'
    do_develop_audit: '产品审批-研发审批'
    do_failed_audit: '产品审批-审批失败'
  instances:
    index: '零件-列表'
    show: '零件-详情'
    new: '零件-添加界面'
    create: '零件-添加'
    edit: '零件-编辑界面'
    update: '零件-编辑'
    destroy: '零件-删除'
    show_version: '零件-历史版本'
    upload_file: '零件-上传图纸界面'
    do_upload_file: '零件-上传图纸'
    edit_file: '零件-编辑图纸界面'
    update_file: '零件-编辑图纸'
    apply: '零件-申请审批'
    do_develop_audit: '零件审批-研发审批'
    do_failed_audit: '零件审批-审批失败'
  technologies:
    index: '工艺文件-列表'
    show: '工艺文件-详情'
    new: '工艺文件-添加界面'
    create: '工艺文件-添加'
    edit: '工艺文件-编辑界面'
    update: '工艺文件-编辑'
    destroy: '工艺文件-删除'
  audits:
    index: '审批-操作台'
    products: '审批-产品审批'
    instances: '审批-零件审批'
  notices:
    receives: '通知-收件箱'
    sends: '通知-发件箱'
    show_notice: '通知-统计详情'
    reply: '通知-回信界面'
    do_reply: '通知-回信'
    new: '通知-发送信息界面'
    create: '通知-发送信息'
    edit: '通知-编辑信息界面'
    update: '通知-编辑信息'
    show: '通知-详情'
developer:
  home:
    index: '主页-我的文件'
    cytoscape: '文件关系图'
    files_search: '全局检索'
  products:
    index: '产品-列表'
    show: '产品-详情'
    show_version: '产品-历史版本'
    upload_file: '产品-上传图纸界面'
    do_upload_file: '产品-上传图纸'
    edit_file: '产品-编辑图纸界面'
    update_file: '产品-编辑图纸'
    apply: '产品-申请审批'
  instances:
    index: '零件-列表'
    show: '零件-详情'
    show_version: '零件-历史版本'
    upload_file: '零件-上传图纸界面'
    do_upload_file: '零件-上传图纸'
    edit_file: '零件-编辑图纸界面'
    update_file: '零件-编辑图纸'
    apply: '零件-申请审批'
  technologies:
    index: '工艺文件-列表'
    show: '工艺文件-详情'
  notices:
    receives: '通知-收件箱'
    sends: '通知-发件箱'
    show_notice: '通知-统计详情'
    reply: '通知-回信界面'
    do_reply: '通知-回信'
    new: '通知-发送信息界面'
    create: '通知-发送信息'
    edit: '通知-编辑信息界面'
    update: '通知-编辑信息'
    show: '通知-详情'
processer:
  home:
    index: '主页-我的文件'
    cytoscape: '文件关系图'
    files_search: '全局检索'
  products:
    index: '产品-列表'
    show: '产品-详情'
    show_version: '产品-历史版本'
    do_flow_audit: '产品审批-流程审批'
    do_active_audit: '产品审批-最终审批'
    do_failed_audit: '产品审批-审批失败'
  instances:
    index: '零件-列表'
    show: '零件-详情'
    show_version: '零件-历史版本'
    do_flow_audit: '零件审批-流程审批'
    do_active_audit: '零件审批-最终审批'
    do_failed_audit: '零件审批-审批失败'
  technologies:
    index: '工艺文件-列表'
    show: '工艺文件-详情'
  audits:
    index: '审批-操作台'
    products: '审批-产品审批'
    instances: '审批-零件审批'
  notices:
    receives: '通知-收件箱'
    sends: '通知-发件箱'
    show_notice: '通知-统计详情'
    reply: '通知-回信界面'
    do_reply: '通知-回信'
    new: '通知-发送信息界面'
    create: '通知-发送信息'
    edit: '通知-编辑信息界面'
    update: '通知-编辑信息'
    show: '通知-详情'